stages:
  - install
  - release

prepare:
  stage: install
  image: registry.vox.dev/getfeedback/cicd-container-images/gitlab-runner-node:stable
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules

publish:
  stage: release
  image: registry.vox.dev/getfeedback/cicd-container-images/gitlab-runner-node:stable
  before_script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
  script:
    - yarn semantic-release
  only:
    - master
